'use client'
import {useEffect,useState} from 'react'
import {Languages,QrCode,X,Copy,Download} from 'lucide-react'
const trEn:Record<string,string>={'DOOMSDAY MARATHON':'DOOMSDAY MARATHON','GÜN KALDI':'DAYS LEFT','MARVEL MARATONUN':'YOUR MARVEL MARATHON','tamamlandı':'complete','görev tamamlandı':'tasks completed','saat kaldı':'hours left','Bugün':'Today','Yapımlar':'Titles','Takvim':'Calendar','Yaklaşanlar':'Upcoming','Tüm Yapımlar':'All Titles','Akıllı Takvim':'Smart Calendar','İzlendi':'Watched','İzlendi olarak işaretle':'Mark as watched','Dizi':'Series','Bölüm':'Episode','Sezon':'Season','Bugün boş gün 🎉':'Free day today 🎉','İstersen yaklaşanlardan birini erkenden bitirebilirsin.':'You can finish an upcoming title early if you want.','İzledikçe kalan program Doomsday’e kadar otomatik yeniden dağıtılır.':'As you watch, the remaining schedule is automatically redistributed until Doomsday.','İzledikçe kalan program Doomsday\'e kadar otomatik yeniden dağıtılır.':'As you watch, the remaining schedule is automatically redistributed until Doomsday.','Daha önce izlediklerin dahil. Dizileri açarak bölümleri tek tek işaretleyebilirsin.':'Includes titles you watched before. Expand series to mark episodes individually.','Bir şey izlediğinde veya kaçırdığında kalan plan otomatik hesaplanır.':'When you watch or miss something, the remaining plan is recalculated automatically.'}
function translateText(text:string,to:'tr'|'en'){if(to==='en'){let s=text;Object.entries(trEn).forEach(([a,b])=>s=s.replaceAll(a,b));return s}let s=text;Object.entries(trEn).forEach(([a,b])=>s=s.replaceAll(b,a));return s}
export default function ClientTools(){const [lang,setLangState]=useState<'tr'|'en'>('tr');const [sync,setSync]=useState(false);const [msg,setMsg]=useState('');const [code,setCode]=useState('')
 useEffect(()=>{const saved=(localStorage.getItem('watchpath-lang')==='en'?'en':'tr');setLangState(saved);const q=new URLSearchParams(location.search).get('sync');if(q){try{const d=JSON.parse(decodeURIComponent(escape(atob(q))));localStorage.setItem('watchpath-progress',JSON.stringify(d.done||{}));if(d.lang)localStorage.setItem('watchpath-lang',d.lang);history.replaceState({},'',location.pathname);location.reload()}catch{}}},[])
 useEffect(()=>{document.documentElement.lang=lang;const run=()=>{document.querySelectorAll('body *').forEach(el=>{if(el.closest('.clientTools,.modalBack,script,style'))return;el.childNodes.forEach(n=>{if(n.nodeType===3&&n.textContent?.trim())n.textContent=translateText(n.textContent,lang)})})};run();const ob=new MutationObserver(run);ob.observe(document.body,{childList:true,subtree:true});return()=>ob.disconnect()},[lang])
 const setLang=(v:'tr'|'en')=>{localStorage.setItem('watchpath-lang',v);setLangState(v)}
 const payload=()=>btoa(unescape(encodeURIComponent(JSON.stringify({v:1,done:JSON.parse(localStorage.getItem('watchpath-progress')||'{}'),lang}))))
 const link=typeof location==='undefined'?'':`${location.origin}${location.pathname}?sync=${payload()}`;const qr=`https://api.qrserver.com/v1/create-qr-code/?size=260x260&data=${encodeURIComponent(link)}`
 const copy=async()=>{await navigator.clipboard.writeText(link);setMsg(lang==='tr'?'Bağlantı kopyalandı ✓':'Link copied ✓')};const imp=()=>{try{const q=code.includes('sync=')?new URL(code).searchParams.get('sync')||'':code;const d=JSON.parse(decodeURIComponent(escape(atob(q.trim()))));localStorage.setItem('watchpath-progress',JSON.stringify(d.done||{}));if(d.lang)localStorage.setItem('watchpath-lang',d.lang);location.reload()}catch{setMsg(lang==='tr'?'Geçersiz kod':'Invalid code')}}
 return <><div className="clientTools"><button onClick={()=>setLang(lang==='tr'?'en':'tr')}><Languages/><b>{lang.toUpperCase()}</b></button><button onClick={()=>setSync(true)}><QrCode/><span>{lang==='tr'?'Aktar':'Transfer'}</span></button></div>{sync&&<div className="modalBack"><section className="syncPanel"><button className="close" onClick={()=>setSync(false)}><X/></button><h2>{lang==='tr'?'Cihazlar Arası Aktarım':'Device Transfer'}</h2><p>{lang==='tr'?'Bu QR kodunu telefonunla okut. İzleme ilerlemen telefona taşınır; hesap gerekmez.':'Scan this QR with your phone. Your watch progress moves to the phone; no account needed.'}</p><img className="qr" src={qr} alt="QR"/><button className="primary" onClick={copy}><Copy/>{lang==='tr'?'Bağlantıyı kopyala':'Copy link'}</button><div className="divider"><span>{lang==='tr'?'veya':'or'}</span></div><textarea value={code} onChange={e=>setCode(e.target.value)} placeholder={lang==='tr'?'Aktarım kodu veya bağlantısı':'Transfer code or link'}/><button className="secondary" onClick={imp}><Download/>{lang==='tr'?'İçe aktar':'Import'}</button>{msg&&<b className="syncMsg">{msg}</b>}<small>{lang==='tr'?'Otomatik senkronizasyon değildir. Yeni değişikliklerden sonra tekrar aktarabilirsin.':'This is not automatic sync. Transfer again after new changes.'}</small></section></div>}</>}
