'use client'

import {useEffect,useState} from 'react'
import {CalendarDays,Sparkles,Trophy} from 'lucide-react'

const p=(x:string)=>`https://image.tmdb.org/t/p/w185${x}`
const branches=[
 {name:'Iron Man',items:[['Iron Man','/78lPtwv72eTNqFW9COBYI0dWDJa.jpg'],['Iron Man 2','/6WBeq4fCfn7AN0o21W9qNcRF2l9.jpg'],['Iron Man 3','/qhPtAc1TKbMPqNvcdXSOn9Bn7hZ.jpg']]},
 {name:'Captain America',items:[['The First Avenger','/vSNxAJTlD0r02V9sPYpOjqDZXUK.jpg'],['The Winter Soldier','/tVFRpFw3xTedgPGqxW0AOI8Qhh0.jpg'],['Civil War','/rAGiXaUfPzY7CDEyNKUofk3Kw2e.jpg']]},
 {name:'Thor',items:[['Thor','/prSfAi1xGrhLQNxVSUFh61xQ4Qy.jpg'],['The Dark World','/wp6OxE4poJ4G7c0U2ZIXasTSMR7.jpg'],['Ragnarok','/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg']]},
 {name:'Avengers',items:[['The Avengers','/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg'],['Age of Ultron','/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg'],['Infinity War','/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg'],['Endgame','/or06FN3Dka5tukK1e9sl16pB3iy.jpg']]}
] as const
const requiredMovies=['iron-man','hulk','iron-man-2','thor','cap1','avengers','iron-man-3','thor2','winter','gotg','ultron','antman','civil','strange','gotg2','homecoming','ragnarok','black-panther','infinity','antman-wasp','captain-marvel','endgame','far-from-home','black-widow','shangchi','eternals','no-way-home','strange2','thor-love','wakanda','quantumania','gotg3','marvels','deadpool-wolverine','brave-new-world','thunderbolts','fantastic-four','brand-new-day']

export default function DoomsdayFinale(){
 const[complete,setComplete]=useState(false)
 useEffect(()=>{const check=()=>{try{const progress=JSON.parse(localStorage.getItem('watchpath-progress')||'{}');setComplete(requiredMovies.every(id=>progress[id]))}catch{setComplete(false)}};check();const timer=setInterval(check,1000);return()=>clearInterval(timer)},[])
 return <section className="finale">
  <div className="treeGlass"><div className="eyebrow">MARVEL YOL AĞACI</div><h2>Doomsday'e giden yollar</h2><div className="tree">{branches.map(branch=><div className="branch" key={branch.name}><b>{branch.name}</b>{branch.items.map(([title,poster])=><div className="movieNode" key={title}><img src={p(poster)} alt=""/><span>{title}</span></div>)}</div>)}</div></div>
  <article className="doomsdayGlass"><div className="poster"><img src="https://image.tmdb.org/t/p/original/6eB2oh1SplddsZYCdayrIdrIGLd.jpg" alt="Avengers: Doomsday poster"/></div><div className="copy"><div className="badge"><Sparkles/> MARATON FİNALİ</div><small>MARVEL STUDIOS</small><h3>AVENGERS</h3><h1>DOOMSDAY</h1><div className="date"><CalendarDays/><div><em>SİNEMA ÇIKIŞ TARİHİ</em><b>18 ARALIK 2026</b></div></div><p>Watchpath maratonunun son durağı. Buraya geldiğinde ana film yolculuğunu tamamlamış olacaksın.</p><div className="actions"><button onClick={()=>window.dispatchEvent(new CustomEvent('watchpath-doomsday-trailer'))}>Fragmanı İzle</button><button onClick={()=>window.dispatchEvent(new CustomEvent('watchpath-doomsday-ticket'))}>Bilet Sayfası</button></div></div></article>
  {complete&&<div className="celebrate"><Trophy/><small>TÜM FİLMLER TAMAMLANDI</small><h2>🎉 Tebrikler, başardın!</h2><p>Doomsday için hazırsın.</p></div>}
  <style jsx>{`.finale{width:min(1080px,calc(100% - 28px));margin:58px auto 150px;display:grid;gap:28px}.treeGlass,.doomsdayGlass,.celebrate{border:1px solid rgba(255,255,255,.17);background:linear-gradient(135deg,rgba(255,255,255,.105),rgba(255,255,255,.028));backdrop-filter:blur(34px) saturate(165%);border-radius:38px;box-shadow:0 32px 90px rgba(0,0,0,.48)}.treeGlass{padding:30px}.eyebrow{color:#ff7e8e;font-size:9px;letter-spacing:.28em}.treeGlass h2{font-size:30px}.tree{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.branch{padding:14px;border:1px solid rgba(255,255,255,.08);border-radius:20px;background:rgba(0,0,0,.16)}.branch>b{display:block;margin-bottom:10px;color:#ff7888;font-size:11px}.movieNode{display:flex;align-items:center;gap:10px;padding:7px;border-radius:12px;background:rgba(255,255,255,.04);margin-top:7px}.movieNode img{width:38px;height:50px;object-fit:cover;border-radius:8px}.movieNode span{font-size:10px;color:#ddd}.doomsdayGlass{display:grid;grid-template-columns:minmax(300px,42%) 1fr;gap:38px;padding:26px}.poster{aspect-ratio:2/3;border-radius:28px;overflow:hidden;background:#050607;border:1px solid rgba(255,255,255,.14)}.poster img{width:100%;height:100%;object-fit:contain;display:block}.copy{align-self:center}.badge{display:inline-flex;align-items:center;gap:7px;padding:9px 13px;border:1px solid rgba(255,255,255,.14);border-radius:999px;background:rgba(255,255,255,.06);font-size:9px;color:#a9efb8}.badge :global(svg){width:14px}.copy small{display:block;margin-top:30px;color:#aaa;letter-spacing:.35em}.copy h3{font-size:28px;letter-spacing:.3em;margin:7px 0 0}.copy h1{font-size:clamp(54px,8vw,86px);line-height:.9;margin:2px 0 28px}.date{display:flex;gap:12px;align-items:center;padding:13px 16px;width:max-content;max-width:100%;border-radius:18px;border:1px solid rgba(255,255,255,.14);background:rgba(255,255,255,.055)}.date :global(svg){width:20px;color:#8ee8a1}.date em{display:block;font-style:normal;font-size:7px;color:#888}.date b{font-size:14px}.copy p{color:#aaa;line-height:1.7;max-width:450px}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:20px}.actions button{color:#fff;padding:11px 14px;border-radius:14px;border:1px solid rgba(255,255,255,.14);background:rgba(255,255,255,.07)}.celebrate{text-align:center;padding:50px}.celebrate :global(svg){width:50px;height:50px;color:#ff7d8b}.celebrate small{display:block;color:#ff8390;letter-spacing:.2em;margin-top:10px}.celebrate h2{font-size:36px;margin:8px}.celebrate p{color:#aaa}@media(max-width:760px){.tree,.doomsdayGlass{grid-template-columns:1fr}.treeGlass,.doomsdayGlass{padding:16px}.poster{max-width:420px;margin:auto}.finale{width:calc(100% - 20px)}}`}</style>
 </section>
}
