export type Lang='tr'|'en'|'de'|'es'|'fr'|'ja'
export const languages:{id:Lang;label:string;flag:string}[]=[{id:'tr',label:'Türkçe',flag:'🇹🇷'},{id:'en',label:'English',flag:'🇬🇧'},{id:'de',label:'Deutsch',flag:'🇩🇪'},{id:'es',label:'Español',flag:'🇪🇸'},{id:'fr',label:'Français',flag:'🇫🇷'},{id:'ja',label:'日本語',flag:'🇯🇵'}]
const d={
tr:{today:'Bugün',titles:'Yapımlar',calendar:'Takvim',marathon:'MARVEL MARATONUN',complete:'tamamlandı',days:'GÜN KALDI',tasks:'görev tamamlandı',hours:'saat kaldı',todayHint:'İzledikçe kalan program Doomsday’e kadar otomatik yeniden dağıtılır.',free:'Bugün boş gün 🎉',freeHint:'İstersen yaklaşanlardan birini erkenden bitirebilirsin.',upcoming:'Yaklaşanlar',all:'Tüm Yapımlar',allHint:'Daha önce izlediklerin dahil. Dizileri açarak bölümleri tek tek işaretleyebilirsin.',smart:'Akıllı Takvim',smartHint:'Bir şey izlediğinde veya kaçırdığında kalan plan otomatik hesaplanır.',watched:'İzlendi',mark:'İzlendi olarak işaretle',series:'Dizi',season:'Sezon',transfer:'Aktar',language:'Dil',search:'Yapım ara...',allFilter:'Tümü',movies:'Filmler',seriesFilter:'Diziler'},
en:{today:'Today',titles:'Titles',calendar:'Calendar',marathon:'YOUR MARVEL MARATHON',complete:'complete',days:'DAYS LEFT',tasks:'tasks completed',hours:'hours left',todayHint:'Your remaining schedule automatically redistributes toward Doomsday as you watch.',free:'Free day 🎉',freeHint:'You can get ahead by watching something upcoming.',upcoming:'Upcoming',all:'All Titles',allHint:'Includes previously watched titles. Expand series to mark episodes individually.',smart:'Smart Calendar',smartHint:'The remaining plan recalculates whenever you watch or miss something.',watched:'Watched',mark:'Mark as watched',series:'Series',season:'Season',transfer:'Transfer',language:'Language',search:'Search titles...',allFilter:'All',movies:'Movies',seriesFilter:'Series'},
de:{today:'Heute',titles:'Titel',calendar:'Kalender',marathon:'DEIN MARVEL-MARATHON',complete:'abgeschlossen',days:'TAGE ÜBRIG',tasks:'Aufgaben erledigt',hours:'Stunden übrig',todayHint:'Dein Zeitplan wird beim Anschauen automatisch bis Doomsday neu verteilt.',free:'Heute frei 🎉',freeHint:'Du kannst einen kommenden Titel vorziehen.',upcoming:'Als Nächstes',all:'Alle Titel',allHint:'Enthält auch bereits gesehene Titel.',smart:'Smarter Kalender',smartHint:'Der Plan wird automatisch neu berechnet.',watched:'Gesehen',mark:'Als gesehen markieren',series:'Serie',season:'Staffel',transfer:'Übertragen',language:'Sprache',search:'Titel suchen...',allFilter:'Alle',movies:'Filme',seriesFilter:'Serien'},
es:{today:'Hoy',titles:'Títulos',calendar:'Calendario',marathon:'TU MARATÓN MARVEL',complete:'completado',days:'DÍAS RESTANTES',tasks:'tareas completadas',hours:'horas restantes',todayHint:'Tu calendario se redistribuye automáticamente hasta Doomsday.',free:'Día libre 🎉',freeHint:'Puedes adelantar un título próximo.',upcoming:'Próximamente',all:'Todos los títulos',allHint:'Incluye títulos ya vistos.',smart:'Calendario inteligente',smartHint:'El plan se recalcula automáticamente.',watched:'Visto',mark:'Marcar como visto',series:'Serie',season:'Temporada',transfer:'Transferir',language:'Idioma',search:'Buscar títulos...',allFilter:'Todos',movies:'Películas',seriesFilter:'Series'},
fr:{today:"Aujourd’hui",titles:'Titres',calendar:'Calendrier',marathon:'TON MARATHON MARVEL',complete:'terminé',days:'JOURS RESTANTS',tasks:'éléments terminés',hours:'heures restantes',todayHint:'Ton planning se redistribue automatiquement jusqu’à Doomsday.',free:'Journée libre 🎉',freeHint:'Tu peux prendre de l’avance.',upcoming:'À venir',all:'Tous les titres',allHint:'Inclut les titres déjà vus.',smart:'Calendrier intelligent',smartHint:'Le planning se recalcule automatiquement.',watched:'Vu',mark:'Marquer comme vu',series:'Série',season:'Saison',transfer:'Transférer',language:'Langue',search:'Rechercher...',allFilter:'Tous',movies:'Films',seriesFilter:'Séries'},
ja:{today:'今日',titles:'作品',calendar:'カレンダー',marathon:'MARVEL マラソン',complete:'完了',days:'日',tasks:'完了',hours:'時間残り',todayHint:'視聴状況に合わせてDoomsdayまでの予定を自動調整します。',free:'今日はお休み 🎉',freeHint:'次の作品を先に見ることもできます。',upcoming:'次の予定',all:'すべての作品',allHint:'視聴済み作品も含まれます。',smart:'スマートカレンダー',smartHint:'進捗に合わせて予定を再計算します。',watched:'視聴済み',mark:'視聴済みにする',series:'シリーズ',season:'シーズン',transfer:'転送',language:'言語',search:'作品を検索...',allFilter:'すべて',movies:'映画',seriesFilter:'シリーズ'}}
export const tx=(lang:Lang,key:keyof typeof d.tr)=>(d[lang] as any)[key]||d.en[key]
