export type Lang='tr'|'en'|'de'|'es'|'fr'|'ja'
export const languages:{id:Lang;label:string;flag:string;locale:string}[]=[
 {id:'tr',label:'Türkçe',flag:'🇹🇷',locale:'tr-TR'},
 {id:'en',label:'English',flag:'🇬🇧',locale:'en-GB'},
 {id:'de',label:'Deutsch',flag:'🇩🇪',locale:'de-DE'},
 {id:'es',label:'Español',flag:'🇪🇸',locale:'es-ES'},
 {id:'fr',label:'Français',flag:'🇫🇷',locale:'fr-FR'},
 {id:'ja',label:'日本語',flag:'🇯🇵',locale:'ja-JP'}
]
export const copy={
tr:{subtitle:'DOOMSDAY MARATONU',marathon:'MARVEL MARATONUN',complete:'tamamlandı',days:'GÜN KALDI',tasks:'görev tamamlandı',hours:'saat kaldı',today:'Bugün',todayHint:"İzledikçe kalan program Doomsday'e kadar otomatik yeniden dağıtılır.",free:'Bugün boş gün 🎉',freeHint:'İstersen yaklaşanlardan birini erkenden bitirebilirsin.',upcoming:'Yaklaşanlar',titles:'Yapımlar',allTitles:'Tüm Yapımlar',allTitlesHint:'Daha önce izlediklerin dahil. Dizileri açarak bölümleri tek tek işaretleyebilirsin.',calendar:'Takvim',smartCalendar:'Akıllı Takvim',smartCalendarHint:'Bir şey izlediğinde veya kaçırdığında kalan plan otomatik hesaplanır.',watched:'İzlendi',markWatched:'İzlendi olarak işaretle',series:'Dizi',season:'Sezon',episode:'Bölüm',hourShort:'sa',minuteShort:'dk',search:'Yapım ara...',filterAll:'Tümü',filterMovies:'Filmler',filterSeries:'Diziler',filterWatched:'İzlenen',filterUnwatched:'İzlenmeyen',noResults:'Bu filtreye uygun yapım bulunamadı.',transfer:'Cihaza Aktar',device:'Cihazlar Arası Aktarım',deviceDesc:'Telefon kameranla QR kodunu okut. İzlediğin film ve bölümler telefona taşınır; hesap gerekmez.',copyLink:'Bağlantıyı kopyala',copied:'Bağlantı kopyalandı ✓',manualImport:'Manuel içe aktarma',import:'İçe aktar',invalid:'Geçersiz aktarım kodu',syncNote:'Otomatik senkronizasyon değildir. Yeni değişikliklerden sonra tekrar aktarabilirsin.',creator:'WATCHPATH TARAFINDAN',portfolio:'Portföyü gör',adline:'Grafik Tasarım · 3D · Dijital Deneyimler'},
en:{subtitle:'DOOMSDAY MARATHON',marathon:'YOUR MARVEL MARATHON',complete:'complete',days:'DAYS LEFT',tasks:'tasks completed',hours:'hours left',today:'Today',todayHint:'Your remaining schedule automatically redistributes toward Doomsday as you watch.',free:'Free day 🎉',freeHint:'You can get ahead by watching something upcoming.',upcoming:'Upcoming',titles:'Titles',allTitles:'All Titles',allTitlesHint:'Includes previously watched titles. Expand series to mark episodes individually.',calendar:'Calendar',smartCalendar:'Smart Calendar',smartCalendarHint:'The remaining plan recalculates whenever you watch or miss something.',watched:'Watched',markWatched:'Mark as watched',series:'Series',season:'Season',episode:'Episode',hourShort:'h',minuteShort:'m',search:'Search titles...',filterAll:'All',filterMovies:'Movies',filterSeries:'Series',filterWatched:'Watched',filterUnwatched:'Unwatched',noResults:'No titles match this filter.',transfer:'Transfer',device:'Device Transfer',deviceDesc:'Scan the QR with your phone camera. Watched movies and episodes move to your phone; no account required.',copyLink:'Copy link',copied:'Link copied ✓',manualImport:'Manual import',import:'Import',invalid:'Invalid transfer code',syncNote:'This is not automatic sync. Transfer again after new changes.',creator:'WATCHPATH BY',portfolio:'View portfolio',adline:'Graphic Design · 3D · Digital Experiences'},
de:{subtitle:'DOOMSDAY-MARATHON',marathon:'DEIN MARVEL-MARATHON',complete:'abgeschlossen',days:'TAGE ÜBRIG',tasks:'Aufgaben erledigt',hours:'Stunden übrig',today:'Heute',todayHint:'Dein restlicher Zeitplan wird beim Anschauen automatisch bis Doomsday neu verteilt.',free:'Heute frei 🎉',freeHint:'Du kannst einen kommenden Titel vorziehen.',upcoming:'Als Nächstes',titles:'Titel',allTitles:'Alle Titel',allTitlesHint:'Bereits gesehene Titel sind enthalten. Serien lassen sich Folge für Folge markieren.',calendar:'Kalender',smartCalendar:'Smarter Kalender',smartCalendarHint:'Der restliche Plan wird automatisch neu berechnet, wenn du etwas ansiehst oder auslässt.',watched:'Gesehen',markWatched:'Als gesehen markieren',series:'Serie',season:'Staffel',episode:'Folge',hourShort:'Std.',minuteShort:'Min.',search:'Titel suchen...',filterAll:'Alle',filterMovies:'Filme',filterSeries:'Serien',filterWatched:'Gesehen',filterUnwatched:'Ungesehen',noResults:'Keine passenden Titel gefunden.',transfer:'Übertragen',device:'Geräteübertragung',deviceDesc:'Scanne den QR-Code mit deinem Handy. Dein Fortschritt wird ohne Konto übertragen.',copyLink:'Link kopieren',copied:'Link kopiert ✓',manualImport:'Manuell importieren',import:'Importieren',invalid:'Ungültiger Übertragungscode',syncNote:'Keine automatische Synchronisierung. Nach Änderungen erneut übertragen.',creator:'WATCHPATH VON',portfolio:'Portfolio ansehen',adline:'Grafikdesign · 3D · Digitale Erlebnisse'},
es:{subtitle:'MARATÓN DOOMSDAY',marathon:'TU MARATÓN MARVEL',complete:'completado',days:'DÍAS RESTANTES',tasks:'tareas completadas',hours:'horas restantes',today:'Hoy',todayHint:'Tu calendario restante se redistribuye automáticamente hasta Doomsday a medida que avanzas.',free:'Día libre 🎉',freeHint:'Puedes adelantar un título próximo.',upcoming:'Próximamente',titles:'Títulos',allTitles:'Todos los títulos',allTitlesHint:'Incluye títulos ya vistos. Abre las series para marcar episodios individualmente.',calendar:'Calendario',smartCalendar:'Calendario inteligente',smartCalendarHint:'El plan restante se recalcula automáticamente cuando ves o te saltas algo.',watched:'Visto',markWatched:'Marcar como visto',series:'Serie',season:'Temporada',episode:'Episodio',hourShort:'h',minuteShort:'min',search:'Buscar títulos...',filterAll:'Todos',filterMovies:'Películas',filterSeries:'Series',filterWatched:'Vistos',filterUnwatched:'No vistos',noResults:'No hay títulos que coincidan con este filtro.',transfer:'Transferir',device:'Transferencia entre dispositivos',deviceDesc:'Escanea el QR con tu teléfono. Tu progreso se transfiere sin necesidad de una cuenta.',copyLink:'Copiar enlace',copied:'Enlace copiado ✓',manualImport:'Importación manual',import:'Importar',invalid:'Código de transferencia no válido',syncNote:'No es sincronización automática. Transfiere de nuevo después de los cambios.',creator:'WATCHPATH POR',portfolio:'Ver portafolio',adline:'Diseño Gráfico · 3D · Experiencias Digitales'},
fr:{subtitle:'MARATHON DOOMSDAY',marathon:'TON MARATHON MARVEL',complete:'terminé',days:'JOURS RESTANTS',tasks:'éléments terminés',hours:'heures restantes',today:"Aujourd’hui",todayHint:'Ton planning restant se redistribue automatiquement jusqu’à Doomsday au fil de ton visionnage.',free:'Journée libre 🎉',freeHint:'Tu peux prendre de l’avance avec un titre à venir.',upcoming:'À venir',titles:'Titres',allTitles:'Tous les titres',allTitlesHint:'Inclut les titres déjà vus. Ouvre les séries pour cocher les épisodes un par un.',calendar:'Calendrier',smartCalendar:'Calendrier intelligent',smartCalendarHint:'Le planning restant se recalcule automatiquement lorsque tu regardes ou sautes quelque chose.',watched:'Vu',markWatched:'Marquer comme vu',series:'Série',season:'Saison',episode:'Épisode',hourShort:'h',minuteShort:'min',search:'Rechercher...',filterAll:'Tous',filterMovies:'Films',filterSeries:'Séries',filterWatched:'Vus',filterUnwatched:'Non vus',noResults:'Aucun titre ne correspond à ce filtre.',transfer:'Transférer',device:'Transfert entre appareils',deviceDesc:'Scanne le QR avec ton téléphone. Ta progression est transférée sans compte.',copyLink:'Copier le lien',copied:'Lien copié ✓',manualImport:'Import manuel',import:'Importer',invalid:'Code de transfert invalide',syncNote:'Ce n’est pas une synchronisation automatique. Transfère à nouveau après les changements.',creator:'WATCHPATH PAR',portfolio:'Voir le portfolio',adline:'Design Graphique · 3D · Expériences Numériques'},
ja:{subtitle:'DOOMSDAY マラソン',marathon:'MARVEL マラソン',complete:'完了',days:'日',tasks:'完了',hours:'時間残り',today:'今日',todayHint:'視聴状況に合わせて、Doomsdayまでの残り予定を自動で再調整します。',free:'今日はお休み 🎉',freeHint:'次の作品を先に見ることもできます。',upcoming:'次の予定',titles:'作品',allTitles:'すべての作品',allTitlesHint:'視聴済み作品も含まれます。シリーズを開いて各エピソードを個別に記録できます。',calendar:'カレンダー',smartCalendar:'スマートカレンダー',smartCalendarHint:'視聴・スキップに合わせて残りの予定を自動で再計算します。',watched:'視聴済み',markWatched:'視聴済みにする',series:'シリーズ',season:'シーズン',episode:'エピソード',hourShort:'時間',minuteShort:'分',search:'作品を検索...',filterAll:'すべて',filterMovies:'映画',filterSeries:'シリーズ',filterWatched:'視聴済み',filterUnwatched:'未視聴',noResults:'条件に一致する作品はありません。',transfer:'転送',device:'デバイス間転送',deviceDesc:'スマホのカメラでQRコードを読み取ると、視聴履歴をアカウントなしで転送できます。',copyLink:'リンクをコピー',copied:'コピーしました ✓',manualImport:'手動インポート',import:'インポート',invalid:'無効な転送コードです',syncNote:'自動同期ではありません。変更後は再度転送してください。',creator:'WATCHPATH BY',portfolio:'ポートフォリオ',adline:'グラフィックデザイン · 3D · デジタル体験'}
} as const
export type CopyKey=keyof typeof copy.tr
export const tx=(lang:Lang,key:CopyKey)=>copy[lang][key]
export const localeFor=(lang:Lang)=>languages.find(x=>x.id===lang)?.locale||'en-GB'
